import { createFileRoute, Link } from "@tanstack/react-router";
import { Navbar } from "@/components/landing/Navbar";
import { MarketBackdrop } from "@/components/landing/MarketBackdrop";
import { CTA, Footer } from "@/components/landing/CTA";
import { FileWarning, AlertTriangle, Brain, TrendingUp, Gavel, Info } from "lucide-react";
import { motion } from "framer-motion";

export const Route = createFileRoute("/disclosures")({
  component: DisclosuresPage,
  head: () => ({
    meta: [
      { title: "Legal Disclosures — MarketIQ" },
      { name: "description", content: "MarketIQ legal disclosures, disclaimers, and risk warnings." },
    ],
  }),
});

function DisclosuresPage() {
  return (
    <main className="relative bg-background text-foreground min-h-screen">
      <MarketBackdrop />
      <Navbar />
      <div className="relative pt-28 px-6 pb-20 max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center gap-3 mb-8"
        >
          <div className="w-10 h-10 rounded-xl bg-gradient-primary flex items-center justify-center shadow-glow">
            <FileWarning className="w-5 h-5 text-primary-foreground" />
          </div>
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Legal Disclosures</h1>
            <p className="text-sm text-muted-foreground">Last updated: May 2026</p>
          </div>
        </motion.div>

        <div className="space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section className="glass rounded-2xl p-6 border border-[var(--bear)]/40">
            <div className="flex items-start gap-3">
              <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: "oklch(0.6 0.2 25 / 0.15)" }}>
                <AlertTriangle className="w-5 h-5" style={{ color: "var(--bear)" }} />
              </div>
              <div>
                <h2 className="text-lg font-semibold mb-2" style={{ color: "var(--bear)" }}>Regulatory Disclosure</h2>
                <p className="text-sm leading-relaxed" style={{ color: "oklch(0.6 0.1 25)" }}>
                  MarketIQ is <strong className="text-foreground" style={{ color: "var(--bear)" }}>not registered</strong> with the Securities and Exchange Board of India (SEBI) as an investment advisor, research analyst, or portfolio manager. The platform operates solely as an educational and informational tool. No content on MarketIQ constitutes a solicitation, recommendation, endorsement, or offer to buy or sell any securities.
                </p>
              </div>
            </div>
          </section>

          <section className="glass rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-3">
              <Brain className="w-4 h-4 text-primary" />
              <h2 className="text-lg font-semibold text-foreground">AI-Generated Content Disclaimer</h2>
            </div>
            <p>Stock scores, buy/hold/sell signals, portfolio analysis, and conversational responses are generated by artificial intelligence models. These models analyse fundamental data, market trends, and your user profile to produce outputs.</p>
            <ul className="space-y-2 mt-3">
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span><strong className="text-foreground">Not guaranteed.</strong> AI outputs may be inaccurate, incomplete, or outdated. They should never be the sole basis for an investment decision.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span><strong className="text-foreground">Not personalised.</strong> While we incorporate your risk profile, AI recommendations do not account for your complete financial situation, tax status, or unique circumstances.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span><strong className="text-foreground">Not real-time.</strong> There may be a delay between market events and when AI models incorporate them into analysis.</span>
              </li>
            </ul>
            <div className="mt-4 p-3 rounded-xl" style={{ background: "oklch(0.6 0.2 25 / 0.08)", border: "1px solid oklch(0.6 0.2 25 / 0.2)" }}>
              <p className="text-xs" style={{ color: "oklch(0.6 0.1 25)" }}>
                <strong>Always conduct your own due diligence.</strong> Read company annual reports, follow regulatory filings, verify data from primary sources, and consult a SEBI-registered advisor before making any investment.
              </p>
            </div>
          </section>

          <section className="glass rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-3">
              <TrendingUp className="w-4 h-4 text-primary" />
              <h2 className="text-lg font-semibold text-foreground">Virtual Portfolio & Performance</h2>
            </div>
            <p>All portfolio tracking, profit/loss calculations, and performance charts on MarketIQ are based on <strong className="text-foreground">simulated virtual trades</strong>. Important caveats:</p>
            <ul className="space-y-2 mt-3">
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span>Virtual trades do not account for brokerage fees, securities transaction tax (STT), GST, SEBI turnover fees, stamp duty, or any other real-world transaction costs.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span>Order execution in virtual trading is instantaneous at the quoted price — real markets involve slippage, order book depth, and liquidity constraints.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span>Performance projections and equity curves use simplified models and should not be interpreted as expected real-world returns.</span>
              </li>
            </ul>
          </section>

          <section className="glass rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-3">
              <Info className="w-4 h-4 text-primary" />
              <h2 className="text-lg font-semibold text-foreground">Data Sources & Accuracy</h2>
            </div>
            <p>MarketIQ aggregates data from multiple public and licensed sources, including exchange feeds and financial data providers. We make reasonable efforts to ensure accuracy, but:</p>
            <ul className="space-y-2 mt-3">
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span>Quotes and price data may be delayed and may not reflect the most current trading activity.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span>Fundamental data (P/E ratios, market capitalisation, quarterly results) is sourced from public filings and may lag behind official exchange disclosures.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--gold)" }} />
                <span>We do not guarantee the timeliness, completeness, or accuracy of any data point displayed on the platform.</span>
              </li>
            </ul>
          </section>

          <section className="glass rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-3">
              <Gavel className="w-4 h-4 text-primary" />
              <h2 className="text-lg font-semibold text-foreground">No Client-Advisor Relationship</h2>
            </div>
            <p>Use of MarketIQ, including interaction with the AI advisor, does not create a client-advisor, fiduciary, or professional relationship between you and the platform, its creators, or its operators. The AI advisor is a <strong className="text-foreground">conversational learning tool</strong>, not a certified financial professional. For personalised financial, tax, or legal advice tailored to your specific situation, please consult qualified professionals registered with the appropriate regulatory bodies.</p>
          </section>

          <section className="glass rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-3">
              <AlertTriangle className="w-4 h-4 text-primary" />
              <h2 className="text-lg font-semibold text-foreground">Risk Warning</h2>
            </div>
            <p>Investing in equity markets and financial instruments involves substantial risk of loss. Key risks include, but are not limited to:</p>
            <ul className="space-y-2 mt-3">
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--bear)" }} />
                <span><strong className="text-foreground">Market risk</strong> — stock prices can fluctuate significantly due to economic conditions, political events, or company-specific factors.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--bear)" }} />
                <span><strong className="text-foreground">Liquidity risk</strong> — some stocks may be difficult to buy or sell at desired prices due to low trading volumes.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--bear)" }} />
                <span><strong className="text-foreground">Concentration risk</strong> — holding a small number of stocks exposes you to company-specific downturns.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0" style={{ background: "var(--bear)" }} />
                <span><strong className="text-foreground">Behavioural risk</strong> — emotional decision-making, such as panic selling or FOMO buying, often leads to poor outcomes.</span>
              </li>
            </ul>
            <div className="mt-4 p-3 rounded-xl" style={{ background: "oklch(0.6 0.2 25 / 0.08)", border: "1px solid oklch(0.6 0.2 25 / 0.2)" }}>
              <p className="text-xs" style={{ color: "oklch(0.6 0.1 25)" }}>
                <strong>Statistic:</strong> According to SEBI's study on individual trading in the equity F&O segment (Jan 2024), approximately 91% of individual traders made net losses during FY23, with an average loss of ₹1.1 lakh per trader. Only 1% of active traders showed consistent profitability over the five-year study period. These figures underscore the importance of education, discipline, and risk management.
              </p>
            </div>
          </section>

          <section className="glass rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-3">
              <Info className="w-4 h-4 text-primary" />
              <h2 className="text-lg font-semibold text-foreground">General Disclaimer</h2>
            </div>
            <p>MarketIQ is provided on an "as is" and "as available" basis without any warranty, express or implied. We disclaim all warranties including merchantability, fitness for a particular purpose, and non-infringement. We are not responsible for any direct, indirect, incidental, special, or consequential damages arising from your use of the platform, even if advised of the possibility of such damages.</p>
          </section>
        </div>

        <div className="mt-10 text-center">
          <Link to="/" className="text-sm text-primary hover:underline">&larr; Back to home</Link>
        </div>
      </div>
      <CTA />
      <Footer />
    </main>
  );
}
