/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AppRouteImport } from './routes/app'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWatchlistRouteImport } from './routes/app.watchlist'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppNewsRouteImport } from './routes/app.news'
import { Route as AppLearnRouteImport } from './routes/app.learn'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppAdvisorRouteImport } from './routes/app.advisor'
import { Route as AppAnalyzeSymbolRouteImport } from './routes/app.analyze.$symbol'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeSymbolRoute = AppAnalyzeSymbolRouteImport.update({
  id: '/analyze/$symbol',
  path: '/analyze/$symbol',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/learn': typeof LearnRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/learn': typeof AppLearnRoute
  '/app/news': typeof AppNewsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
  '/app/analyze/$symbol': typeof AppAnalyzeSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/learn': typeof LearnRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/learn': typeof AppLearnRoute
  '/app/news': typeof AppNewsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app': typeof AppIndexRoute
  '/app/analyze/$symbol': typeof AppAnalyzeSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/learn': typeof LearnRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/learn': typeof AppLearnRoute
  '/app/news': typeof AppNewsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
  '/app/analyze/$symbol': typeof AppAnalyzeSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-advisor'
    | '/app'
    | '/features'
    | '/how-it-works'
    | '/learn'
    | '/sign-in'
    | '/sign-up'
    | '/app/advisor'
    | '/app/discover'
    | '/app/learn'
    | '/app/news'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/watchlist'
    | '/app/'
    | '/app/analyze/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-advisor'
    | '/features'
    | '/how-it-works'
    | '/learn'
    | '/sign-in'
    | '/sign-up'
    | '/app/advisor'
    | '/app/discover'
    | '/app/learn'
    | '/app/news'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/watchlist'
    | '/app'
    | '/app/analyze/$symbol'
  id:
    | '__root__'
    | '/'
    | '/ai-advisor'
    | '/app'
    | '/features'
    | '/how-it-works'
    | '/learn'
    | '/sign-in'
    | '/sign-up'
    | '/app/advisor'
    | '/app/discover'
    | '/app/learn'
    | '/app/news'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/watchlist'
    | '/app/'
    | '/app/analyze/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAdvisorRoute: typeof AiAdvisorRoute
  AppRoute: typeof AppRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LearnRoute: typeof LearnRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/watchlist': {
      id: '/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/news': {
      id: '/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisor': {
      id: '/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyze/$symbol': {
      id: '/app/analyze/$symbol'
      path: '/analyze/$symbol'
      fullPath: '/app/analyze/$symbol'
      preLoaderRoute: typeof AppAnalyzeSymbolRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppLearnRoute: typeof AppLearnRoute
  AppNewsRoute: typeof AppNewsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnalyzeSymbolRoute: typeof AppAnalyzeSymbolRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppLearnRoute: AppLearnRoute,
  AppNewsRoute: AppNewsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnalyzeSymbolRoute: AppAnalyzeSymbolRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAdvisorRoute: AiAdvisorRoute,
  AppRoute: AppRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LearnRoute: LearnRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
